### ISSUE TITLE
Exception while creating FTLFrame

### ISSUE THREAD

**Issue by Perry1990** [Vhati/ftl-profile-editor#105]
Compiled in IntelliJ. Editor refused to start. Here is the exception:

06:54:53.879 [AWT-EventQueue-0] ERROR net.blerf.ftl.FTLProfileEditor - Exception while creating FTLFrame.
java.lang.NullPointerException: null
	at javax.swing.ImageIcon.<init>(ImageIcon.java:217) ~[?:1.8.0_151]
	at net.blerf.ftl.ui.FTLFrame.<init>(FTLFrame.java:112) ~[main/:?]
	at net.blerf.ftl.FTLProfileEditor.guiInit(FTLProfileEditor.java:198) [main/:?]
	at net.blerf.ftl.FTLProfileEditor.access$000(FTLProfileEditor.java:29) [main/:?]
	at net.blerf.ftl.FTLProfileEditor$1.run(FTLProfileEditor.java:44) [main/:?]
	...

Process finished with exit code 1

**Comment by Malanius** [comment]
For me it is working fine in IntelliJ.

How did you import the project?

**Comment by Vhati** [comment]
I'm not familiar with IntelliJ, but that's a weird place to glitch.

> at net.blerf.ftl.ui.FTLFrame.(FTLFrame.java:112)

.
[Source](https://github.com/Vhati/ftl-profile-editor/blob/81bbf72ba4be7bdc6b112831aace5073927fee05/src/main/java/net/blerf/ftl/ui/FTLFrame.java#L112): FTLFrame.java (circa 2017-11-27)

	110: private ImageIcon openIcon = new ImageIcon( ClassLoader.getSystemResource( "open.gif" ) );
	111: private ImageIcon saveIcon = new ImageIcon( ClassLoader.getSystemResource( "save.gif" ) );
	112: private ImageIcon unlockIcon = new ImageIcon( ClassLoader.getSystemResource( "unlock.png" ) );
	113: private ImageIcon aboutIcon = new ImageIcon( ClassLoader.getSystemResource( "about.gif" ) );
	114: private ImageIcon updateIcon = new ImageIcon( ClassLoader.getSystemResource( "update.gif" ) );

It had to have found two images already.
